version: '2.0'
services:
  es5.6:
    image: registry.forchange.cn/public/es-with-xpack:5.6.16
    container_name: es5.6
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:

      - /Users/lan/repos/github/docker-images/elasticsearch/5.6/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/lan/repos/github/docker-images/elasticsearch/5.6/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - share_net
networks:
  share_net:
