FROM elasticsearch:7.3.1

RUN ./bin/elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.3.1/elasticsearch-analysis-ik-7.3.1.zip

EXPOSE 9200
EXPOSE 9300
