version: "3"
services:

  postgres:
    image: postgres
    networks:
      - gatling_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - gatling_network
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions


networks:
  gatling_network:
