version: "3"
services:

  postgres:
    image: postgres
    restart: always
    networks:
      - sonar_net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  sonarqube:
    image: sonarqube:8.2-community
    restart: always
    ports:
      - "9001:9000"
    networks:
      - sonar_net
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions


networks:
  sonar_net:

