version: '3'
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_SERVER_HOST=buglan.org
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=github-client-id
      - DRONE_GITHUB_CLIENT_SECRET=github-client-secret
      - DRONE_LOGS_PRETTY=true
      - DRONE_RPC_SECRET=secretkey
      - DRONE_USER_CREATE=username:BUGLAN,admin:true
      - DRONE_USER_FILTER=qing-long
      # - DRONE_REPOSITORY_FILTER=qing-long,BUGLAN,SeluneXscd
      # - DRONE_DATABASE_DRIVER=mysql
      # - DRONE_DATABASE_DATASOURCE=root:root@tcp(176.122.132.132:3306)/drone?parseTime=true

      #  drone-agent:
      #      image: drone/agent:1
      #      restart: always
      #      depends_on:
      #        - drone-server
      #      volumes:
      #        - /var/run/docker.sock:/var/run/docker.sock
      #      environment:
      #        - DRONE_PRC_SERVER=http://buglan.org
      #        - DRONE_SECRET=secretkey
      #        - DRONE_RUNNER_CAPACITY=2
      #        - DRONE_LOGS_DEBUG=true
