version: '3'
services:
  drone-server:
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_SERVER_HOST=buglan.org
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=github-client-id
      - DRONE_GITHUB_CLIENT_SECRET=github-client-secret
      - DRONE_LOGS_PRETTY=true
      - DRONE_RPC_SECRET=secretkey
      - DRONE_USER_CREATE=username:BUGLAN,admin:true
      - DRONE_USER_FILTER=qing-long
      # - DRONE_SECRET_SECRET=558f3eacbfd5928157cbfe34823ab921
      # - DRONE_SECRET_ENDPOINT=http://0.0.0.0:3000
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=root:root@tcp(0.0.0.0:3306)/drone?parseTime=true
  mysql5.7:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drone
