global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.108:9090']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['192.168.1.108:9104']

  - job_name: 'gin-demo'
    static_configs:
      - targets: ['192.168.1.108:8080']
