global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ms'
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'demo'
    scrape_interval: 8s
    scrape_timeout: 8s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'node_exporter'
    scrape_interval: 8s
    scrape_timeout: 8s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9100']