version: '3'
services:
  web:
    image: gitea/gitea:1.8.3
    container_name: gitea
    restart: always
    ports:
      - 3000:3000
      - 22:22
    volumes:
        - ./data:/data
    depends_on:
      - db
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db/:/var/lib/mysql