FROM elasticsearch:7.2.0

RUN bin/elasticsearch-plugin install -b https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.2.0/elasticsearch-analysis-ik-7.2.0.zip

EXPOSE 9200
EXPOSE 9300
